// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkinData;

#nullable disable

namespace SkinData.Migrations
{
    [DbContext(typeof(VenToolsContext))]
    [Migration("20220728192347_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Skin", b =>
                {
                    b.Property<string>("SkinId")
                        .HasColumnType("text");

                    b.Property<string>("AccessGuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Breed")
                        .HasColumnType("int");

                    b.Property<int>("Coverage")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastViewed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Pose")
                        .HasColumnType("int");

                    b.Property<string>("SkinName")
                        .HasColumnType("text");

                    b.Property<string>("SkinUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SkinId");

                    b.ToTable("Skin", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
